version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: CGono.NagBot.TG.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    restart: always