FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expose ports
ENV ASPNETCORE_URLS http://*:5216
EXPOSE 5216

# Run
ENTRYPOINT ["dotnet", "CGono.NagBot.TG.Api.dll"]